[build]
builder = "DOCKERFILE"
dockerfilePath = "Day06-C401-TeamE4/backend/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
